# version: "3"
# services:
#   client:
#     image: "bijay4725sahoo/multi-client"
#     mem_limit: 128m
#     hostname: client
#   server:
#     image: "bijay4725sahoo/multi-server"
#     mem_limit: 128m
#     hostname: api
#     environment:
#       - REDIS_HOST=$REDIS_HOST
#       - REDIS_PORT=$REDIS_PORT
#       - PGUSER=$PGUSER
#       - PGHOST=$PGHOST
#       - PGDATABASE=$PGDATABASE
#       - PGPASSWORD=$PGPASSWORD
#       - PGPORT=$PGPORT
#   worker:
#     image: "bijay4725sahoo/multi-worker"
#     mem_limit: 128m
#     hostname: worker
#     environment:
#       - REDIS_HOST=$REDIS_HOST
#       - REDIS_PORT=$REDIS_PORT
#   nginx:
#     image: "bijay4725sahoo/multi-nginx"
#     mem_limit: 128m
#     hostname: nginx
#     ports:
#       - "80:80"

version: "3"
services:
  client:
    image: "cygnetops/multi-client-10-14"
    mem_limit: 128m
    hostname: client
  server:
    image: "cygnetops/multi-server-10-14"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "cygnetops/multi-worker-10-14"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "cygnetops/multi-nginx-10-14"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
